### ISSUE TITLE
text_normalize() remove all alphabet characters

### ISSUE THREAD

**Issue by indiejoseph** [Naozumi520/Bert-VITS2-Cantonese-Yue#3]
https://github.com/Naozumi520/Bert-VITS2-Cantonese-Yue/blob/36790b0f1f8824d91b0c834131eed8b8f1a01637/text/chinese.py#L109

Is it intended?

**Comment by Naozumi520** [comment]
> https://github.com/Naozumi520/Bert-VITS2-Cantonese-Yue/blob/36790b0f1f8824d91b0c834131eed8b8f1a01637/text/chinese.py#L109
> 
> Is it intended?

Yes, a cleaner can only process one language only, and in `chinese.py` any Chinese punctuation will be replaced with English one.
If a sentence contain English words, the inference webui have "Mixed" language which can split the sentence and use different cleaner. But it is necessary to remove the alphabet characters for the Chinese cleaner.

**Comment by indiejoseph** [comment]
Thanks for clarify, I should dig deeper to know how it works first.
